piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nginx-deployment'
  namespace: 'argocd'
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      valueFiles:
      - values.yaml
      path: helm/
  project: 'default'
